var nombre = "Juan";
var edad = 25;
var esEstud = true;
console.log("Nombre:", nombre);
console.log("Edad:", edad);
console.log("Es estudiante:", esEstud);
var num1 = 10;
var num2 = 5;
var suma = num1 + num2;
var resta = num1 - num2;
var mult = num1 * num2;
var divis = num1 / num2;
console.log("Suma:", suma);
console.log("Resta:", resta);
console.log("Multiplicación:", mult);
console.log("División:", divis);
var saludo = "Hola";
var nomComp = saludo + " " + nombre;
console.log(nomComp);